title: Ahmad Munawar | Engineer
description: >
  Personal portfolio and blog of Ahmad Munawar, Engineer.
permalink: ':title/'
baseurl: "/eng_ahmad.github.io"
url: ""
# Author Settings
author: Ahmad Munawar
author-img: david-freeman.jpg # replace with your photo filename
about-author: Engineer passionate about solving real-world problems through technology and innovation.
social-twitter:
social-facebook:
social-github: engr-ahmad-munawar
social-linkedin:
social-email:
# Disqus
discus-identifier: ahmad-munawar
# Tracker
analytics:
# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
paginate: 8
paginate_path: "/blog/page/:num"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
